name: async_lesson
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

dependencies:

  dio: ^5.2.1+1
  http: ^1.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

dev_dependencies:

  build_runner: ^2.4.6
  freezed: ^2.4.0
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
